name: Build

on:
  push:
  pull_request:

jobs:
  build-linter-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Ensure gradlew is executable
        run: chmod +x app/gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app

      - name: Generate code coverage report
        working-directory: app
        run: ./gradlew jacocoTestReport

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          workingDirectory: app
          debug: true
